import {
  AlertTriangle,
  HandCoins,
  Bed,
  Bone,
  BookOpen,
  Building2,
  Car,
  Clapperboard,
  Coffee,
  Coins,
  Dumbbell,
  FileText,
  Fuel,
  Gift,
  GraduationCap,
  HeartHandshake,
  HeartPulse,
  HelpCircle,
  Home,
  Hospital,
  Laptop,
  ScanFace,
  MapPin,
  Mic2,
  Palette,
  ParkingMeter,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  ReceiptText,
  Repeat,
  Scissors,
  Scroll,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBasket,
  Sofa,
  Stethoscope,
  Luggage,
  Laugh,
  Train,
  Umbrella,
  Utensils,
  Wallet,
  Wifi,
  Wrench,
  Zap,
} from "lucide-react";

export const categoryIcons = {
  alert_triangle: AlertTriangle,
  hand_coins: HandCoins,
  bed: Bed,
  bone: Bone,
  book_open: BookOpen,
  building_2: Building2,
  car: Car,
  clapperboard: Clapperboard,
  coffee: Coffee,
  coins: Coins,
  dumbbell: Dumbbell,
  file_text: FileText,
  fuel: Fuel,
  gift: Gift,
  graduation_cap: GraduationCap,
  heart_handshake: HeartHandshake,
  heart_pulse: HeartPulse,
  help_circle: HelpCircle,
  home: Home,
  hospital: Hospital,
  laptop: Laptop,
  scan_face: ScanFace,
  map_pin: MapPin,
  mic_2: Mic2,
  palette: Palette,
  parking_meter: ParkingMeter,
  phone: Phone,
  piggy_bank: PiggyBank,
  pill: Pill,
  plane: Plane,
  receipt_text: ReceiptText,
  repeat: Repeat,
  scissors: Scissors,
  scroll: Scroll,
  shield: Shield,
  shield_check: ShieldCheck,
  shirt: Shirt,
  shopping_basket: ShoppingBasket,
  sofa: Sofa,
  stethoscope: Stethoscope,
  luggage: Luggage,
  laugh: Laugh,
  train: Train,
  umbrella: Umbrella,
  utensils: Utensils,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
  default: HelpCircle, // Fallback icon
};
