import {
  Home,
  Scroll,
  Umbrella,
  Zap,
  Wrench,
  GasPump,
  Train,
  MapPin,
  ShieldCheck,
  ParkingMeter,
  Plane,
  Bed,
  Suitcase,
  Car,
  Shield,
  ShoppingBasket,
  ForkKnife,
  Coffee,
  Stethoscope,
  Hospital,
  Pill,
  Tooth,
  Dumbbell,
  Coins,
  PiggyBank,
  FileText,
  ShieldCheck,
  Clapperboard,
  Repeat,
  Mic2,
  Palette,
  GraduationCap,
  BookOpen,
  Building2,
  Shirt,
  Laptop,
  MakeupBrush,
  Sofa,
  Gift,
  HeartHandshake,
  AlertTriangle,
  Wallet,
  ReceiptText,
  Phone,
  Wifi,
  Bone,
  HeartPulse,
  Scissors,
  Bank,
} from "lucide-react";

export const categoryIcons = [
  [
    {
      id: 0,
      camel_case_icon: "CircleHelp",
      parent_category: "Uncategorized",
    },
    {
      id: 42,
      camel_case_icon: "Home",
      parent_category: "Housing",
    },
    {
      id: 43,
      camel_case_icon: "Scroll",
      parent_category: "Housing",
    },
    {
      id: 44,
      camel_case_icon: "Umbrella",
      parent_category: "Housing",
    },
    {
      id: 45,
      camel_case_icon: "Zap",
      parent_category: "Housing",
    },
    {
      id: 46,
      camel_case_icon: "Wrench",
      parent_category: "Housing",
    },
    {
      id: 47,
      camel_case_icon: "GasPump",
      parent_category: "Transportation",
    },
    {
      id: 48,
      camel_case_icon: "Train",
      parent_category: "Transportation",
    },
    {
      id: 49,
      camel_case_icon: "MapPin",
      parent_category: "Transportation",
    },
    {
      id: 50,
      camel_case_icon: "Wrench",
      parent_category: "Transportation",
    },
    {
      id: 51,
      camel_case_icon: "ShieldCheck",
      parent_category: "Transportation",
    },
    {
      id: 52,
      camel_case_icon: "ParkingMeter",
      parent_category: "Transportation",
    },
    {
      id: 53,
      camel_case_icon: "Plane",
      parent_category: "Travel",
    },
    {
      id: 54,
      camel_case_icon: "Bed",
      parent_category: "Travel",
    },
    {
      id: 55,
      camel_case_icon: "Suitcase",
      parent_category: "Travel",
    },
    {
      id: 56,
      camel_case_icon: "Car",
      parent_category: "Travel",
    },
    {
      id: 57,
      camel_case_icon: "Shield",
      parent_category: "Travel",
    },
    {
      id: 58,
      camel_case_icon: "ShoppingBasket",
      parent_category: "Food & Dining",
    },
    {
      id: 59,
      camel_case_icon: "Utensils",
      parent_category: "Food & Dining",
    },
    {
      id: 60,
      camel_case_icon: "Coffee",
      parent_category: "Food & Dining",
    },
    {
      id: 61,
      camel_case_icon: "Stethoscope",
      parent_category: "Health & Wellness",
    },
    {
      id: 62,
      camel_case_icon: "Hospital",
      parent_category: "Health & Wellness",
    },
    {
      id: 63,
      camel_case_icon: "Pill",
      parent_category: "Health & Wellness",
    },
    {
      id: 64,
      camel_case_icon: "Tooth",
      parent_category: "Health & Wellness",
    },
    {
      id: 65,
      camel_case_icon: "Dumbbell",
      parent_category: "Health & Wellness",
    },
    {
      id: 66,
      camel_case_icon: "Coins",
      parent_category: "Finances",
    },
    {
      id: 67,
      camel_case_icon: "BankPiggy",
      parent_category: "Finances",
    },
    {
      id: 68,
      camel_case_icon: "TextFile",
      parent_category: "Finances",
    },
    {
      id: 69,
      camel_case_icon: "ShieldCheck",
      parent_category: "Root",
    },
    {
      id: 70,
      camel_case_icon: "Clapperboard",
      parent_category: "Entertainment",
    },
    {
      id: 71,
      camel_case_icon: "Repeat",
      parent_category: "Entertainment",
    },
    {
      id: 72,
      camel_case_icon: "2Mic",
      parent_category: "Entertainment",
    },
    {
      id: 73,
      camel_case_icon: "Palette",
      parent_category: "Entertainment",
    },
    {
      id: 74,
      camel_case_icon: "CapGraduation",
      parent_category: "Education",
    },
    {
      id: 75,
      camel_case_icon: "OpenBook",
      parent_category: "Education",
    },
    {
      id: 76,
      camel_case_icon: "2Building",
      parent_category: "Education",
    },
    {
      id: 77,
      camel_case_icon: "Shirt",
      parent_category: "Shopping & Personal",
    },
    {
      id: 78,
      camel_case_icon: "Laptop",
      parent_category: "Shopping & Personal",
    },
    {
      id: 79,
      camel_case_icon: "BrushMakeup",
      parent_category: "Shopping & Personal",
    },
    {
      id: 80,
      camel_case_icon: "Sofa",
      parent_category: "Shopping & Personal",
    },
    {
      id: 81,
      camel_case_icon: "Gift",
      parent_category: "Gifts & Donations",
    },
    {
      id: 82,
      camel_case_icon: "HandshakeHeart",
      parent_category: "Gifts & Donations",
    },
    {
      id: 83,
      camel_case_icon: "TriangleAlert",
      parent_category: "Miscellaneous",
    },
    {
      id: 84,
      camel_case_icon: "Wallet",
      parent_category: "Miscellaneous",
    },
    {
      id: 85,
      camel_case_icon: "TextReceipt",
      parent_category: "Miscellaneous",
    },
    {
      id: 86,
      camel_case_icon: "Phone",
      parent_category: "Communication",
    },
    {
      id: 87,
      camel_case_icon: "Wifi",
      parent_category: "Communication",
    },
    {
      id: 88,
      camel_case_icon: "Bone",
      parent_category: "Pet Expenses",
    },
    {
      id: 89,
      camel_case_icon: "HeartPulse",
      parent_category: "Pet Expenses",
    },
    {
      id: 90,
      camel_case_icon: "Scissors",
      parent_category: "Pet Expenses",
    },
    {
      id: 91,
      camel_case_icon: "Bank",
      parent_category: "Emergency & Contingency",
    },
    {
      id: 92,
      camel_case_icon: "Wrench",
      parent_category: "Emergency & Contingency",
    },
  ],
];
